using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace DotNetNote.Endpoints;

public static class IsoCountriesEndpoint
{
    public static void MapIsoCountriesEndpoint(this IEndpointRouteBuilder endpoints)
    {
        var isoCountries = new List<IsoCountry>
        {
            new("Afghanistan", "AF, AFG"),
            new("Aland Islands", "AX, ALA"),
            new("Albania", "AL, ALB"),
            new("Algeria", "DZ, DZA"),
            new("American Samoa", "AS, ASM"),
            new("Andorra", "AD, AND"),
            new("Angola", "AO, AGO"),
            new("Anguilla", "AI, AIA"),
            new("Antarctica", "AQ, ATA"),
            new("Antigua and Barbuda", "AG, ATG"),
            new("Argentina", "AR, ARG"),
            new("Armenia", "AM, ARM"),
            new("Aruba", "AW, ABW"),
            new("Australia", "AU, AUS"),
            new("Austria", "AT, AUT"),
            new("Azerbaijan", "AZ, AZE"),
            new("Bahamas, The", "BS, BHS"),
            new("Bahrain", "BH, BHR"),
            new("Bangladesh", "BD, BGD"),
            new("Barbados", "BB, BRB"),
            new("Belarus", "BY, BLR"),
            new("Belgium", "BE, BEL"),
            new("Belize", "BZ, BLZ"),
            new("Benin", "BJ, BEN"),
            new("Bermuda", "BM, BMU"),
            new("Bhutan", "BT, BTN"),
            new("Bolivia", "BO, BOL"),
            new("Bonaire, Sint Eustatius and Saba", "BQ, BES"),
            new("Bosnia and Herzegovina", "BA, BIH"),
            new("Botswana", "BW, BWA"),
            new("Bouvet Island", "BV, BVT"),
            new("Brazil", "BR, BRA"),
            new("British Indian Ocean Territory", "IO, IOT"),
            new("British Virgin Islands", "VG, VGB"),
            new("Brunei", "BN, BRN"),
            new("Bulgaria", "BG, BGR"),
            new("Burkina Faso", "BF, BFA"),
            new("Burma", "MM, MMR"),
            new("Burundi", "BI, BDI"),
            new("Cambodia", "KH, KHM"),
            new("Cameroon", "CM, CMR"),
            new("Canada", "CA, CAN"),
            new("Cape Verde", "CV, CPV"),
            new("Cayman Islands", "KY, CYM"),
            new("Central African Republic", "CF, CAF"),
            new("Chad", "TD, TCD"),
            new("Chile", "CL, CHL"),
            new("China", "CN, CHN"),
            new("Christmas Island", "CX, CXR"),
            new("Cocos (Keeling) Islands", "CC, CCK"),
            new("Colombia", "CO, COL"),
            new("Comoros", "KM, COM"),
            new("Congo, Democratic Republic of the", "CD, COD"),
            new("Congo, Republic of the", "CG, COG"),
            new("Cook Islands", "CK, COK"),
            new("Costa Rica", "CR, CRI"),
            new("Cote d'Ivoire", "CI, CIV"),
            new("Croatia", "HR, HRV"),
            new("Cuba", "CU, CUB"),
            new("Curacao", "CW, CUW"),
            new("Cyprus", "CY, CYP"),
            new("Czech Republic", "CZ, CZE"),
            new("Denmark", "DK, DNK"),
            new("Djibouti", "DJ, DJI"),
            new("Dominica", "DM, DMA"),
            new("Dominican Republic", "DO, DOM"),
            new("East Timor", "TL, TLS"),
            new("Ecuador", "EC, ECU"),
            new("Egypt", "EG, EGY"),
            new("El Salvador", "SV, SLV"),
            new("Equatorial Guinea", "GQ, GNQ"),
            new("Eritrea", "ER, ERI"),
            new("Estonia", "EE, EST"),
            new("Ethiopia", "ET, ETH"),
            new("Falkland Islands (Islas Malvinas)", "FK, FLK"),
            new("Faroe Islands", "FO, FRO"),
            new("Fiji", "FJ, FJI"),
            new("Finland", "FI, FIN"),
            new("France", "FR, FRA"),
            new("French Guiana", "GF, GUF"),
            new("French Polynesia", "PF, PYF"),
            new("French Southern and Antarctic Lands", "TF, ATF"),
            new("Gabon", "GA, GAB"),
            new("Gambia, The", "GM, GMB"),
            new("Georgia", "GE, GEO"),
            new("Germany", "DE, DEU"),
            new("Ghana", "GH, GHA"),
            new("Gibraltar", "GI, GIB"),
            new("Greece", "GR, GRC"),
            new("Greenland", "GL, GRL"),
            new("Grenada", "GD, GRD"),
            new("Guadeloupe", "GP, GLP"),
            new("Guam", "GU, GUM"),
            new("Guatemala", "GT, GTM"),
            new("Guernsey", "GG, GGY"),
            new("Guinea", "GN, GIN"),
            new("Guinea-Bissau", "GW, GNB"),
            new("Guyana", "GY, GUY"),
            new("Haiti", "HT, HTI"),
            new("Heard Island and McDonald Islands", "HM, HMD"),
            new("Holy See (Vatican City)", "VA, VAT"),
            new("Honduras", "HN, HND"),
            new("Hong Kong", "HK, HKG"),
            new("Hungary", "HU, HUN"),
            new("Iceland", "IS, ISL"),
            new("India", "IN, IND"),
            new("Indonesia", "ID, IDN"),
            new("Iran", "IR, IRN"),
            new("Iraq", "IQ, IRQ"),
            new("Ireland", "IE, IRL"),
            new("Isle of Man", "IM, IMN"),
            new("Israel", "IL, ISR"),
            new("Italy", "IT, ITA"),
            new("Jamaica", "JM, JAM"),
            new("Japan", "JP, JPN"),
            new("Jersey", "JE, JEY"),
            new("Jordan", "JO, JOR"),
            new("Kazakhstan", "KZ, KAZ"),
            new("Kenya", "KE, KEN"),
            new("Kiribati", "KI, KIR"),
            new("Korea, North", "KP, PRK"),
            new("Korea, South", "KR, KOR"),
            new("Kosovo", "XK, XKX"),
            new("Kuwait", "KW, KWT"),
            new("Kyrgyzstan", "KG, KGZ"),
            new("Laos", "LA, LAO"),
            new("Latvia", "LV, LVA"),
            new("Lebanon", "LB, LBN"),
            new("Lesotho", "LS, LSO"),
            new("Liberia", "LR, LBR"),
            new("Libya", "LY, LBY"),
            new("Liechtenstein", "LI, LIE"),
            new("Lithuania", "LT, LTU"),
            new("Luxembourg", "LU, LUX"),
            new("Macau", "MO, MAC"),
            new("Macedonia", "MK, MKD"),
            new("Madagascar", "MG, MDG"),
            new("Malawi", "MW, MWI"),
            new("Malaysia", "MY, MYS"),
            new("Maldives", "MV, MDV"),
            new("Mali", "ML, MLI"),
            new("Malta", "MT, MLT"),
            new("Marshall Islands", "MH, MHL"),
            new("Martinique", "MQ, MTQ"),
            new("Mauritania", "MR, MRT"),
            new("Mauritius", "MU, MUS"),
            new("Mayotte", "YT, MYT"),
            new("Mexico", "MX, MEX"),
            new("Micronesia, Federated States of", "FM, FSM"),
            new("Moldova", "MD, MDA"),
            new("Monaco", "MC, MCO"),
            new("Mongolia", "MN, MNG"),
            new("Montenegro", "ME, MNE"),
            new("Montserrat", "MS, MSR"),
            new("Morocco", "MA, MAR"),
            new("Mozambique", "MZ, MOZ"),
            new("Namibia", "NA, NAM"),
            new("Nauru", "NR, NRU"),
            new("Nepal", "NP, NPL"),
            new("Netherlands", "NL, NLD"),
            new("Zimbabwe", "ZW, ZWE"),
        };

        endpoints.MapGet("/v1/isocountries", () => Results.Ok(isoCountries));
    }

    private record IsoCountry(string Country, string ValidCodes);
}